
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.util.regex.*;
import javax.swing.JOptionPane; 
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import static java.lang.Thread.sleep;
import java.util.Calendar;
import static java.util.Calendar.DAY_OF_MONTH;
import static java.util.Calendar.HOUR;
import static java.util.Calendar.MINUTE;
import static java.util.Calendar.MONTH;
import static java.util.Calendar.SECOND;
import static java.util.Calendar.YEAR;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;
import project.ConnectionProvider;
import javax.swing.JOptionPane;
import java.sql.Driver;
import java.text.SimpleDateFormat;
import net.proteanit.sql.DbUtils;
import java.util.Date;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sourabh
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        
         clock();       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        whole_panel = new javax.swing.JPanel();
        admin_panel = new javax.swing.JPanel();
        admin_icon = new javax.swing.JLabel();
        online = new javax.swing.JLabel();
        lbldate = new javax.swing.JLabel();
        lbltime = new javax.swing.JLabel();
        menu_panel = new javax.swing.JPanel();
        dashboard_panel = new javax.swing.JPanel();
        dashboard = new javax.swing.JLabel();
        user_panel = new javax.swing.JPanel();
        user = new javax.swing.JLabel();
        parking_slots_panel = new javax.swing.JPanel();
        parking_slots = new javax.swing.JLabel();
        parking_panel = new javax.swing.JPanel();
        parking = new javax.swing.JLabel();
        reports_panel = new javax.swing.JPanel();
        reports = new javax.swing.JLabel();
        settings_panel = new javax.swing.JPanel();
        settings = new javax.swing.JLabel();
        about_panel = new javax.swing.JPanel();
        about = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel13 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        total_slots_panel = new javax.swing.JPanel();
        total_slots = new javax.swing.JLabel();
        slots = new javax.swing.JLabel();
        slots_available_panel = new javax.swing.JPanel();
        slots_available = new javax.swing.JLabel();
        ava_slots = new javax.swing.JLabel();
        slots_occupied_panel = new javax.swing.JPanel();
        slots_occupied = new javax.swing.JLabel();
        occ_slots = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        choose_dob = new com.toedter.calendar.JDateChooser();
        dob = new javax.swing.JLabel();
        choose_gender = new javax.swing.JComboBox<>();
        gender = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        write_address = new javax.swing.JTextField();
        contact = new javax.swing.JLabel();
        write_contact = new javax.swing.JTextField();
        name = new javax.swing.JLabel();
        write_name = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        write_slotno = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        choose_status = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        reg_no = new javax.swing.JLabel();
        owner_name = new javax.swing.JLabel();
        vehicle_type = new javax.swing.JLabel();
        mobile = new javax.swing.JLabel();
        rate = new javax.swing.JLabel();
        alloted_slot = new javax.swing.JLabel();
        write_reg_no = new javax.swing.JTextField();
        write_ownername = new javax.swing.JTextField();
        write_mobile = new javax.swing.JTextField();
        choose_type = new javax.swing.JComboBox<>();
        write_alloted_slot = new javax.swing.JTextField();
        choose_rate = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        vehicle_in = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        in_table = new javax.swing.JTable();
        vehicle_out = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        out_table = new javax.swing.JTable();
        delete = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1000, 700));

        whole_panel.setMinimumSize(new java.awt.Dimension(1920, 1080));
        whole_panel.setPreferredSize(new java.awt.Dimension(1920, 1080));
        whole_panel.setRequestFocusEnabled(false);
        whole_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        admin_panel.setBackground(new java.awt.Color(51, 51, 51));
        admin_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        admin_icon.setBackground(new java.awt.Color(0, 0, 0));
        admin_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin.jpg"))); // NOI18N
        admin_panel.add(admin_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 80));

        online.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        online.setForeground(new java.awt.Color(255, 255, 255));
        online.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images.jpg"))); // NOI18N
        online.setText("ONLINE");
        admin_panel.add(online, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 100, 20));

        lbldate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbldate.setForeground(new java.awt.Color(255, 255, 255));
        lbldate.setText("Date");
        admin_panel.add(lbldate, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 20, 120, -1));

        lbltime.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbltime.setForeground(new java.awt.Color(255, 255, 255));
        lbltime.setText("Time");
        admin_panel.add(lbltime, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 50, 120, -1));

        whole_panel.add(admin_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 80));

        menu_panel.setBackground(new java.awt.Color(0, 153, 153));
        menu_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dashboard.setFont(new java.awt.Font("Albertus Medium", 1, 24)); // NOI18N
        dashboard.setText("      Dashboard");
        dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout dashboard_panelLayout = new javax.swing.GroupLayout(dashboard_panel);
        dashboard_panel.setLayout(dashboard_panelLayout);
        dashboard_panelLayout.setHorizontalGroup(
            dashboard_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashboard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        dashboard_panelLayout.setVerticalGroup(
            dashboard_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        menu_panel.add(dashboard_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 200, 45));

        user_panel.setPreferredSize(new java.awt.Dimension(200, 45));

        user.setFont(new java.awt.Font("Albertus Medium", 1, 24)); // NOI18N
        user.setText("          User");
        user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout user_panelLayout = new javax.swing.GroupLayout(user_panel);
        user_panel.setLayout(user_panelLayout);
        user_panelLayout.setHorizontalGroup(
            user_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(user, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        user_panelLayout.setVerticalGroup(
            user_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(user, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        menu_panel.add(user_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 200, 45));

        parking_slots.setFont(new java.awt.Font("Albertus Medium", 1, 24)); // NOI18N
        parking_slots.setText("    Parking Slots");
        parking_slots.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                parking_slotsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout parking_slots_panelLayout = new javax.swing.GroupLayout(parking_slots_panel);
        parking_slots_panel.setLayout(parking_slots_panelLayout);
        parking_slots_panelLayout.setHorizontalGroup(
            parking_slots_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(parking_slots, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        parking_slots_panelLayout.setVerticalGroup(
            parking_slots_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(parking_slots, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        menu_panel.add(parking_slots_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 200, 45));
        parking_slots_panel.getAccessibleContext().setAccessibleName("");

        parking.setFont(new java.awt.Font("Albertus Medium", 1, 24)); // NOI18N
        parking.setText("        Parking");
        parking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                parkingMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout parking_panelLayout = new javax.swing.GroupLayout(parking_panel);
        parking_panel.setLayout(parking_panelLayout);
        parking_panelLayout.setHorizontalGroup(
            parking_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(parking, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        parking_panelLayout.setVerticalGroup(
            parking_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(parking, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        menu_panel.add(parking_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 200, 45));

        reports.setFont(new java.awt.Font("Albertus Medium", 1, 24)); // NOI18N
        reports.setText("        Reports");
        reports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reportsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout reports_panelLayout = new javax.swing.GroupLayout(reports_panel);
        reports_panel.setLayout(reports_panelLayout);
        reports_panelLayout.setHorizontalGroup(
            reports_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(reports, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        reports_panelLayout.setVerticalGroup(
            reports_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(reports, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        menu_panel.add(reports_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 200, 45));

        settings.setFont(new java.awt.Font("Albertus Medium", 1, 24)); // NOI18N
        settings.setText("        Settings");
        settings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout settings_panelLayout = new javax.swing.GroupLayout(settings_panel);
        settings_panel.setLayout(settings_panelLayout);
        settings_panelLayout.setHorizontalGroup(
            settings_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(settings, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        settings_panelLayout.setVerticalGroup(
            settings_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(settings, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        menu_panel.add(settings_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 200, 45));

        about.setFont(new java.awt.Font("Albertus Medium", 1, 24)); // NOI18N
        about.setText("         About");
        about.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout about_panelLayout = new javax.swing.GroupLayout(about_panel);
        about_panel.setLayout(about_panelLayout);
        about_panelLayout.setHorizontalGroup(
            about_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(about, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        about_panelLayout.setVerticalGroup(
            about_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(about, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        menu_panel.add(about_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 200, 45));

        whole_panel.add(menu_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 200, 600));

        jPanel19.setBackground(new java.awt.Color(102, 102, 102));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        total_slots_panel.setBackground(new java.awt.Color(255, 255, 153));
        total_slots_panel.setPreferredSize(new java.awt.Dimension(190, 110));

        total_slots.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        total_slots.setText("Total  slots");

        slots.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        slots.setText("00");

        javax.swing.GroupLayout total_slots_panelLayout = new javax.swing.GroupLayout(total_slots_panel);
        total_slots_panel.setLayout(total_slots_panelLayout);
        total_slots_panelLayout.setHorizontalGroup(
            total_slots_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(total_slots_panelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(total_slots)
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, total_slots_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(slots)
                .addGap(70, 70, 70))
        );
        total_slots_panelLayout.setVerticalGroup(
            total_slots_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, total_slots_panelLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(slots)
                .addGap(18, 18, 18)
                .addComponent(total_slots)
                .addContainerGap())
        );

        jPanel19.add(total_slots_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 190, 110));

        slots_available_panel.setBackground(new java.awt.Color(153, 153, 153));
        slots_available_panel.setPreferredSize(new java.awt.Dimension(190, 110));

        slots_available.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        slots_available.setText(" Slots Available");

        ava_slots.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        ava_slots.setText("00");

        javax.swing.GroupLayout slots_available_panelLayout = new javax.swing.GroupLayout(slots_available_panel);
        slots_available_panel.setLayout(slots_available_panelLayout);
        slots_available_panelLayout.setHorizontalGroup(
            slots_available_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slots_available_panelLayout.createSequentialGroup()
                .addGroup(slots_available_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(slots_available_panelLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(slots_available))
                    .addGroup(slots_available_panelLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(ava_slots)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        slots_available_panelLayout.setVerticalGroup(
            slots_available_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, slots_available_panelLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(ava_slots)
                .addGap(18, 18, 18)
                .addComponent(slots_available)
                .addContainerGap())
        );

        jPanel19.add(slots_available_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 190, 110));

        slots_occupied_panel.setBackground(new java.awt.Color(255, 51, 51));

        slots_occupied.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        slots_occupied.setText("  Slots occupied");

        occ_slots.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        occ_slots.setText("00");

        javax.swing.GroupLayout slots_occupied_panelLayout = new javax.swing.GroupLayout(slots_occupied_panel);
        slots_occupied_panel.setLayout(slots_occupied_panelLayout);
        slots_occupied_panelLayout.setHorizontalGroup(
            slots_occupied_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slots_occupied_panelLayout.createSequentialGroup()
                .addGroup(slots_occupied_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(slots_occupied_panelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(slots_occupied))
                    .addGroup(slots_occupied_panelLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(occ_slots)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        slots_occupied_panelLayout.setVerticalGroup(
            slots_occupied_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, slots_occupied_panelLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(occ_slots)
                .addGap(18, 18, 18)
                .addComponent(slots_occupied)
                .addContainerGap())
        );

        jPanel19.add(slots_occupied_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 40, 190, 110));

        jLabel33.setIcon(new javax.swing.ImageIcon("C:\\Users\\sourabh\\Desktop\\icons\\multi-storey-car-park.jpg")); // NOI18N
        jPanel19.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 790, 630));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, 830, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, 620, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab3", jPanel13);

        jPanel20.setBackground(new java.awt.Color(255, 255, 255));
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "User", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24))); // NOI18N

        dob.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dob.setText("Date of Birth");

        choose_gender.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        choose_gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", " ", " " }));
        choose_gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choose_genderActionPerformed(evt);
            }
        });

        gender.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        gender.setText("Gender");

        address.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        address.setText("Address");

        write_address.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        write_address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                write_addressActionPerformed(evt);
            }
        });

        contact.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        contact.setText("Contact  ");

        write_contact.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        write_contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                write_contactActionPerformed(evt);
            }
        });
        write_contact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                write_contactKeyPressed(evt);
            }
        });

        name.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        name.setText("Name");

        write_name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        submit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(gender)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(choose_gender, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(contact)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                        .addComponent(write_contact, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(name)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(write_name, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(address)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(write_address, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(dob)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(choose_dob, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(57, 57, 57))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(submit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name)
                    .addComponent(write_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contact)
                    .addComponent(write_contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(write_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(choose_gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gender))
                .addGap(55, 55, 55)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(choose_dob, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dob))
                .addGap(32, 32, 32)
                .addComponent(submit)
                .addContainerGap())
        );

        jPanel20.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 490, 500));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\sourabh\\Desktop\\icons\\istockphoto-1224849939-612x612.jpg")); // NOI18N
        jPanel20.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 610));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab4", jPanel14);

        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add Slot", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Slot Number");

        write_slotno.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Status");

        choose_status.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        choose_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose", "Active", "Inactive" }));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("Add");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(129, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(95, 95, 95)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(write_slotno)
                    .addComponent(choose_status, 0, 258, Short.MAX_VALUE))
                .addGap(80, 80, 80))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(write_slotno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(choose_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
        );

        jPanel15.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 700, 260));

        jLabel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel15.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -2, 800, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\sourabh\\Desktop\\icons\\istockphoto-1224849939-612x612.jpg")); // NOI18N
        jPanel15.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 620));

        jTabbedPane1.addTab("tab5", jPanel15);

        jPanel22.setBackground(new java.awt.Color(255, 255, 255));
        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Add vehicles");
        jPanel22.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, -1, -1));

        reg_no.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        reg_no.setText("Vehicle Registration No.");
        jPanel22.add(reg_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, -1));

        owner_name.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        owner_name.setText("Owner's Name");
        jPanel22.add(owner_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 180, 40));

        vehicle_type.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        vehicle_type.setText("Vehicle Type");
        jPanel22.add(vehicle_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, -1, 50));

        mobile.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        mobile.setText("Contact");
        jPanel22.add(mobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, -1, 40));

        rate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rate.setText("Rate");
        jPanel22.add(rate, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, -1, -1));

        alloted_slot.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        alloted_slot.setText("Slot Alloted");
        jPanel22.add(alloted_slot, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 460, -1, 40));

        write_reg_no.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel22.add(write_reg_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 250, -1));

        write_ownername.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        write_ownername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                write_ownernameActionPerformed(evt);
            }
        });
        jPanel22.add(write_ownername, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, 250, -1));

        write_mobile.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel22.add(write_mobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, 250, -1));

        choose_type.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        choose_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Car", "Bike", "Autorikshaw", "Other", "" }));
        choose_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choose_typeActionPerformed(evt);
            }
        });
        jPanel22.add(choose_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, -1, -1));

        write_alloted_slot.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel22.add(write_alloted_slot, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 470, 250, -1));

        choose_rate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        choose_rate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "20", "50" }));
        jPanel22.add(choose_rate, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 410, 130, -1));

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Parking", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24))); // NOI18N

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setText("Add Vehicle");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(238, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(213, 213, 213))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(411, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addContainerGap())
        );

        jPanel22.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 620, 490));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/istockphoto-1224849939-612x612.jpg"))); // NOI18N
        jPanel22.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 610));

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab6", jPanel16);

        jPanel23.setBackground(new java.awt.Color(255, 255, 255));
        jPanel23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        vehicle_in.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        vehicle_in.setForeground(new java.awt.Color(255, 255, 255));
        vehicle_in.setText("Vehicle In");
        jPanel23.add(vehicle_in, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, -1, -1));

        in_table.setBackground(new java.awt.Color(0, 153, 153));
        in_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Registration No.", "Name", "Date", "Type", "Slot", "Amount"
            }
        ));
        in_table.setRowHeight(25);
        in_table.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                in_tableComponentShown(evt);
            }
        });
        jScrollPane1.setViewportView(in_table);

        jPanel23.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 800, 160));

        vehicle_out.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        vehicle_out.setForeground(new java.awt.Color(255, 255, 255));
        vehicle_out.setText("Vehicle Out");
        jPanel23.add(vehicle_out, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, -1, -1));

        out_table.setBackground(new java.awt.Color(0, 153, 153));
        out_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Registration No.", "Name", "Date", "Type", "Slot", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        out_table.setRowHeight(25);
        jScrollPane2.setViewportView(out_table);

        jPanel23.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 800, 190));

        delete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        delete.setText("Delete");
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
        });
        jPanel23.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 270, 110, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/istockphoto-1224849939-612x612.jpg"))); // NOI18N
        jPanel23.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 800, 600));

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab7", jPanel17);

        jPanel24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Username");
        jPanel24.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 110, 20));

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel24.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 230, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Password");
        jPanel24.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 90, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Contact");
        jPanel24.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 110, -1));

        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel24.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 310, 230, -1));

        jPasswordField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPanel24.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, 230, -1));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Settings", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24))); // NOI18N

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Logout");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Change Password");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jButton1)
                .addGap(76, 76, 76)
                .addComponent(jButton2)
                .addContainerGap(104, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(233, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(39, 39, 39))
        );

        jPanel24.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 580, 340));
        jPanel24.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -2, 810, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/istockphoto-1224849939-612x612.jpg"))); // NOI18N
        jPanel24.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 830, 630));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel24, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab1", jPanel11);

        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(0, 153, 153));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "About Us", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 478, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 273, Short.MAX_VALUE)
        );

        jPanel12.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 490, 310));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/istockphoto-1224849939-612x612.jpg"))); // NOI18N
        jPanel12.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 810, 630));

        jTabbedPane1.addTab("tab2", jPanel12);

        whole_panel.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 800, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(whole_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 999, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(whole_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void clock()
    {
        Thread clock ;
        clock = new Thread()
        {
            public void run()
            {
                try{
                    while(true)
                    {
                        Calendar cal=new GregorianCalendar();
                        int day=cal.get(Calendar.DAY_OF_MONTH);
                        int month=cal.get(Calendar.MONTH)+1;
                        int year=cal.get(Calendar.YEAR);
                        
                        int second=cal.get(Calendar.SECOND);
                        int minute=cal.get(Calendar.MINUTE);
                        int hour=cal.get(Calendar.HOUR);
                        
                        String time=( hour +":"+ minute+":" + second);
                        String date=(day+"/"+month+"/"+year);
                        
                            sleep(1000);
                            
                             lbldate.setText(date);
                             lbltime.setText(time);
                    }
                } catch (Exception e) {
                            JOptionPane.showMessageDialog(rootPane, e);
                }
                       
            }
        };    
        clock.start();
    }
            
    
    
    private void dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardMouseClicked
        // TODO add your handling code here:
         jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_dashboardMouseClicked

    private void userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userMouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_userMouseClicked

    private void parking_slotsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_parking_slotsMouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_parking_slotsMouseClicked

    private void parkingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_parkingMouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_parkingMouseClicked

    private void reportsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportsMouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(4);
        try
        {
            
            Connection con =ConnectionProvider.getCon();
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select * from parking");
            in_table.setModel(DbUtils.resultSetToTableModel(rs));
            in_table.setAutoResizeMode(in_table.AUTO_RESIZE_OFF);
            ResultSet rst=st.executeQuery("select * from parking");
            out_table.setModel(DbUtils.resultSetToTableModel(rst));
            out_table.setAutoResizeMode(out_table.AUTO_RESIZE_OFF);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"connection error");
        } 
    }//GEN-LAST:event_reportsMouseClicked

    private void settingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsMouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(5);
    }//GEN-LAST:event_settingsMouseClicked

    private void aboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutMouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(6);
    }//GEN-LAST:event_aboutMouseClicked

    private void choose_genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choose_genderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_choose_genderActionPerformed

    private void write_contactKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_write_contactKeyPressed
        // TODO add your handling code here:
        String Contact=write_contact.getText();
        int length=Contact.length();
        char c=evt.getKeyChar();
        
        if(evt.getKeyChar()>='0'&&evt.getKeyChar()<='9'){
            if(length<10){
                write_contact.setEditable(true);
        }else{
            write_contact.setEditable(false);
        }
         
        } else
        {
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE||evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
                write_contact.setEditable(true);
            }else{
                write_contact.setEditable(false);
            }
        }
    }//GEN-LAST:event_write_contactKeyPressed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        String name=write_name.getText();
        String contact=write_contact.getText();
        String address=write_address.getText();
        String gender=(String)choose_gender.getSelectedItem();
        String dob=(String)choose_dob.getDateFormatString();
        try
        {
            Connection con=ConnectionProvider.getCon();
            Statement st=con.createStatement();
            
            st.executeUpdate("insert into user values('"+name+"','"+contact+"','"+address+"','"+gender+"','"+dob+"')");
            JOptionPane.showMessageDialog(null,"Succesfully updated");
            setVisible(false);
            new Home().setVisible(true);
        }
        catch(Exception e)
        {
           JOptionPane.showMessageDialog(null,e);
            setVisible(false);
            new Home().setVisible(true);
        }
         
        
    }//GEN-LAST:event_submitActionPerformed

    private void write_ownernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_write_ownernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_write_ownernameActionPerformed

    private void choose_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choose_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_choose_typeActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void write_addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_write_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_write_addressActionPerformed

    private void write_contactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_write_contactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_write_contactActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new login().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         try
        {
            Connection con=ConnectionProvider.getCon();
            
            Statement st=con.createStatement();
           // st.executeUpdate("create table if not exists parking(reg_no varchar(10)primary key, own_name varchar(20), veh_type varchar(10), contact int(10)unique key, rate int(3),slot varchar(3)unique key)");
            
            //st.executeUpdate("insert into parking values('"+reg_no+"','"+own_name+"','"+veh_type+"','"+contact+"','"+rate+"','"+slot+"')");
           // JOptionPane.showMessageDialog(null,"Succesfully updated");
            setVisible(false);
            new Home().setVisible(true);
        }
        catch(Exception e)
        {
           JOptionPane.showMessageDialog(null,e);
            setVisible(false);
            new Home().setVisible(true);
        }
        String reg_no=write_reg_no.getText();
        String own_name=write_ownername.getText();
        String veh_type=(String)choose_type.getSelectedItem();
        String contact=write_mobile.getText();
        String rate=(String)choose_rate.getSelectedItem();
        String slot=write_alloted_slot.getText();
        try
        {
        Connection con=ConnectionProvider.getCon();
            
          Statement st=con.createStatement();
          
            
          st.executeUpdate("insert into parking values('"+reg_no+"','"+own_name+"','"+veh_type+"','"+contact+"','"+rate+"','"+slot+"')");
          JOptionPane.showMessageDialog(null,"Succesfully updated");
          setVisible(false);
          new Home().setVisible(true);
        }
        catch(Exception e)
        {
           JOptionPane.showMessageDialog(null,e);
            setVisible(false);
            new Home().setVisible(true);
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void in_tableComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_in_tableComponentShown
        // TODO add your handling code here:
       
    }//GEN-LAST:event_in_tableComponentShown

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String slotno=write_slotno.getText();
        String status=(String)choose_status.getSelectedItem();
        
        try
        {
            Connection con=ConnectionProvider.getCon();
            Statement st=con.createStatement();
            
            st.executeUpdate("insert into parking_slots values('"+slotno+"','"+status+"')");
            JOptionPane.showMessageDialog(null,"Succesfully updated");
            setVisible(false);
            new Home().setVisible(true);
        }
        catch(Exception e)
        {
           JOptionPane.showMessageDialog(null,e);
            setVisible(false);
            new Home().setVisible(true);
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
        // TODO add your handling code here:
       try{
            int row=in_table.getSelectedRow();
            String id = (in_table.getModel().getValueAt(row, 0).toString());

         int p = JOptionPane.showConfirmDialog(null,JOptionPane.YES_NO_OPTION);
         if (p==0){
           Connection con=ConnectionProvider.getCon();
            Statement st=con.createStatement();
            
            st.executeUpdate("delete from parking where reg_no=?");
        JOptionPane.showMessageDialog(null,"d");
        }
        }catch(Exception e){
         JOptionPane.showMessageDialog(rootPane, e);
    }
       
        
    }//GEN-LAST:event_deleteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel about;
    private javax.swing.JPanel about_panel;
    private javax.swing.JLabel address;
    private javax.swing.JLabel admin_icon;
    private javax.swing.JPanel admin_panel;
    private javax.swing.JLabel alloted_slot;
    private javax.swing.JLabel ava_slots;
    private com.toedter.calendar.JDateChooser choose_dob;
    private javax.swing.JComboBox<String> choose_gender;
    private javax.swing.JComboBox<String> choose_rate;
    private javax.swing.JComboBox<String> choose_status;
    private javax.swing.JComboBox<String> choose_type;
    private javax.swing.JLabel contact;
    private javax.swing.JLabel dashboard;
    private javax.swing.JPanel dashboard_panel;
    private javax.swing.JButton delete;
    private javax.swing.JLabel dob;
    private javax.swing.JLabel gender;
    private javax.swing.JTable in_table;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel lbldate;
    private javax.swing.JLabel lbltime;
    private javax.swing.JPanel menu_panel;
    private javax.swing.JLabel mobile;
    private javax.swing.JLabel name;
    private javax.swing.JLabel occ_slots;
    private javax.swing.JLabel online;
    private javax.swing.JTable out_table;
    private javax.swing.JLabel owner_name;
    private javax.swing.JLabel parking;
    private javax.swing.JPanel parking_panel;
    private javax.swing.JLabel parking_slots;
    private javax.swing.JPanel parking_slots_panel;
    private javax.swing.JLabel rate;
    private javax.swing.JLabel reg_no;
    private javax.swing.JLabel reports;
    private javax.swing.JPanel reports_panel;
    private javax.swing.JLabel settings;
    private javax.swing.JPanel settings_panel;
    private javax.swing.JLabel slots;
    private javax.swing.JLabel slots_available;
    private javax.swing.JPanel slots_available_panel;
    private javax.swing.JLabel slots_occupied;
    private javax.swing.JPanel slots_occupied_panel;
    private javax.swing.JButton submit;
    private javax.swing.JLabel total_slots;
    private javax.swing.JPanel total_slots_panel;
    private javax.swing.JLabel user;
    private javax.swing.JPanel user_panel;
    private javax.swing.JLabel vehicle_in;
    private javax.swing.JLabel vehicle_out;
    private javax.swing.JLabel vehicle_type;
    private javax.swing.JPanel whole_panel;
    private javax.swing.JTextField write_address;
    private javax.swing.JTextField write_alloted_slot;
    private javax.swing.JTextField write_contact;
    private javax.swing.JTextField write_mobile;
    private javax.swing.JTextField write_name;
    private javax.swing.JTextField write_ownername;
    private javax.swing.JTextField write_reg_no;
    private javax.swing.JTextField write_slotno;
    // End of variables declaration//GEN-END:variables

}
